language: python

python:
  - "2.7"
  - "3.5"

env:
  - DJANGO_VERSION="<1.9"
  - DJANGO_VERSION="<1.10"
  - DJANGO_VERSION="<1.11"

install:
  - pip install "Django$DJANGO_VERSION"

script:
  - python tools.py test
